version: "3.8"
services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: change-me-please   # ⚠️ change-moi avant de lancer
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    restart: unless-stopped
